### ISSUE TITLE
componentType 5125 is unknown

### ISSUE THREAD

**Issue by riccardogiorato** [TimvanScherpenzeel/gltf-to-usdz#7]
Can't convert this model can you help me out?

It gives me this error while converting to usda. "componentType 5125 is unknown"

And then the usda to usdz converter says: "There are 0 vertices in this asset file 'shoe.usda'."

[shoe.zip](https://github.com/TimvanScherpenzeel/gltf-to-usdz/files/2361353/shoe.zip)

**Comment by TimvanScherpenzeel** [comment]
Have you tried removing the space from the texture filename? That can sometimes cause issues.

Can you post the outputted USDA file?

**Comment by TimvanScherpenzeel** [comment]
Closing this due to a lack of response.
